apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-app
  labels:
    app: cicd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo-app
  template:
    metadata:
      labels:
        app: cicd-demo-app
    spec:
      containers:
        - name: cicd-demo-app
          image: yourdockerhubusername/cicd-demo-app:latest   # <-- must match image Jenkins pushed
          ports:
            - containerPort: 80
