[ci_master]
ci-master ansible_host=13.202.80.174 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[ci_agent]
ci-agent ansible_host=43.204.218.183 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3